"""Add featured courses

Revision ID: 3a3ac6e4af8d
Revises: f481ab435aaf
Create Date: 2026-07-10 01:46:50.320745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3ac6e4af8d'
down_revision: Union[str, None] = 'f481ab435aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('courses', sa.Column('featured_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'featured_order')
    op.drop_column('courses', 'is_featured')
    # ### end Alembic commands ###
