"""add support message attachments

Revision ID: 3ac37d7818c2
Revises: 94a00d63b87e
Create Date: 2026-08-24 11:12:52.549836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac37d7818c2'
down_revision: Union[str, None] = '94a00d63b87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('attachment_storage_key', sa.String(length=1000), nullable=True))
    op.add_column('support_messages', sa.Column('attachment_file_name', sa.String(length=255), nullable=True))
    op.add_column('support_messages', sa.Column('attachment_mime_type', sa.String(length=255), nullable=True))
    op.add_column('support_messages', sa.Column('attachment_file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_messages', 'attachment_file_size_bytes')
    op.drop_column('support_messages', 'attachment_mime_type')
    op.drop_column('support_messages', 'attachment_file_name')
    op.drop_column('support_messages', 'attachment_storage_key')
    # ### end Alembic commands ###
