"""add auto_renew and pending_plan_id to user_subscriptions

Revision ID: aee9e3d77651
Revises: 6241b42aaece
Create Date: 2026-07-06 02:56:17.010922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee9e3d77651'
down_revision: Union[str, None] = '6241b42aaece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.execute('UPDATE user_subscriptions SET auto_renew = true')
    op.alter_column('user_subscriptions', 'auto_renew', nullable=False)
    
    op.add_column('user_subscriptions', sa.Column('pending_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_user_subscriptions_pending_plan_id', 'user_subscriptions', 'subscription_plans', ['pending_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_subscriptions_pending_plan_id', 'user_subscriptions', type_='foreignkey')
    op.drop_column('user_subscriptions', 'pending_plan_id')
    op.drop_column('user_subscriptions', 'auto_renew')
    # ### end Alembic commands ###
