"""Add icon_name and description to course_catalogs

Revision ID: c4692b2c76e8
Revises: 4ea9ff628f0e
Create Date: 2026-07-10 02:00:35.050751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4692b2c76e8'
down_revision: Union[str, None] = '4ea9ff628f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_catalogs', sa.Column('icon_name', sa.String(length=255), nullable=True))
    op.add_column('course_catalogs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_catalogs', 'description')
    op.drop_column('course_catalogs', 'icon_name')
    # ### end Alembic commands ###
