"""contact us updates and unique enrolled courses

Revision ID: f481ab435aaf
Revises: aee9e3d77651
Create Date: 2026-07-10 01:39:04.079358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f481ab435aaf'
down_revision: Union[str, None] = 'aee9e3d77651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    category_enum = sa.Enum('GENERAL', 'MENTORSHIP', 'PRICING', 'COURSES', name='contact_us_category_enum')
    category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('contact_us_messages', sa.Column('category', category_enum, nullable=True))
    op.add_column('contact_us_messages', sa.Column('subject', sa.String(length=255), nullable=True))
    
    # Remove duplicates from user_course_access before adding unique constraint
    op.execute('''
        DELETE FROM user_course_access a USING (
            SELECT MIN(ctid) as ctid, user_id, course_id
            FROM user_course_access 
            GROUP BY user_id, course_id HAVING COUNT(*) > 1
        ) b
        WHERE a.user_id = b.user_id 
        AND a.course_id = b.course_id 
        AND a.ctid <> b.ctid
    ''')
    
    # Remove duplicates from user_course_progress before adding unique constraint
    op.execute('''
        DELETE FROM user_course_progress a USING (
            SELECT MIN(ctid) as ctid, user_id, course_id
            FROM user_course_progress 
            GROUP BY user_id, course_id HAVING COUNT(*) > 1
        ) b
        WHERE a.user_id = b.user_id 
        AND a.course_id = b.course_id 
        AND a.ctid <> b.ctid
    ''')

    op.create_unique_constraint('uq_user_course_access', 'user_course_access', ['user_id', 'course_id'])
    op.create_unique_constraint('uq_user_course_progress', 'user_course_progress', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_course_progress', 'user_course_progress', type_='unique')
    op.drop_constraint('uq_user_course_access', 'user_course_access', type_='unique')
    op.drop_column('contact_us_messages', 'subject')
    op.drop_column('contact_us_messages', 'category')
    category_enum = sa.Enum('GENERAL', 'MENTORSHIP', 'PRICING', 'COURSES', name='contact_us_category_enum')
    category_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
